"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 05:07:20.548970
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


GEO_TABLES = ("opportunity_areas", "demands", "properties")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.String(length=16), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_name'), 'audit_events', ['name'], unique=False)
    op.create_table('opportunity_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_opportunity_areas_city'), 'opportunity_areas', ['city'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('destination', sa.String(length=254), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_destination'), 'otp_challenges', ['destination'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('active_role', sa.String(length=16), nullable=False),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lng', sa.Float(), nullable=True),
    sa.Column('home_label', sa.String(length=120), nullable=True),
    sa.Column('home_area_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['home_area_id'], ['opportunity_areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('device_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_hash')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('business_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('preferred_cities', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('size_min_sqft', sa.Integer(), nullable=True),
    sa.Column('size_max_sqft', sa.Integer(), nullable=True),
    sa.Column('registration_id', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('demands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('reason', sa.String(length=24), nullable=False),
    sa.Column('reason_note', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('locality', sa.String(length=120), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('verified_support_count', sa.Integer(), nullable=False),
    sa.Column('pending_support_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_support_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['opportunity_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demands_area_id'), 'demands', ['area_id'], unique=False)
    op.create_index(op.f('ix_demands_author_id'), 'demands', ['author_id'], unique=False)
    op.create_index(op.f('ix_demands_category'), 'demands', ['category'], unique=False)
    op.create_index(op.f('ix_demands_status'), 'demands', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=400), nullable=True),
    sa.Column('link', sa.String(length=240), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('size_value', sa.Float(), nullable=True),
    sa.Column('size_unit', sa.String(length=8), nullable=False),
    sa.Column('size_sqft', sa.Float(), nullable=True),
    sa.Column('price_type', sa.String(length=8), nullable=False),
    sa.Column('price_amount', sa.BigInteger(), nullable=True),
    sa.Column('price_negotiable', sa.Boolean(), nullable=False),
    sa.Column('availability', sa.String(length=8), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=240), nullable=True),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('verification_level', sa.String(length=16), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stale_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['opportunity_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_area_id'), 'properties', ['area_id'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_table('reward_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('ref_type', sa.String(length=16), nullable=True),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('voucher_code', sa.String(length=24), nullable=True),
    sa.Column('expected_unlock_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'action', 'ref_id', name='uq_reward_once')
    )
    op.create_index(op.f('ix_reward_ledger_user_id'), 'reward_ledger', ['user_id'], unique=False)
    op.create_table('saved_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'ref_id', 'category', name='uq_saved_item')
    )
    op.create_index(op.f('ix_saved_items_user_id'), 'saved_items', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_status'), 'verifications', ['status'], unique=False)
    op.create_index(op.f('ix_verifications_subject_id'), 'verifications', ['subject_id'], unique=False)
    op.create_table('demand_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('demand_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=280), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demand_id', 'user_id', name='uq_interest_once')
    )
    op.create_index(op.f('ix_demand_interests_demand_id'), 'demand_interests', ['demand_id'], unique=False)
    op.create_index(op.f('ix_demand_interests_user_id'), 'demand_interests', ['user_id'], unique=False)
    op.create_table('demand_supports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('demand_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('device_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demand_id', 'user_id', name='uq_support_once')
    )
    op.create_index(op.f('ix_demand_supports_demand_id'), 'demand_supports', ['demand_id'], unique=False)
    op.create_index(op.f('ix_demand_supports_user_id'), 'demand_supports', ['user_id'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('demand_id', sa.UUID(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['opportunity_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_demand_id'), 'inquiries', ['demand_id'], unique=False)
    op.create_index(op.f('ix_inquiries_from_user_id'), 'inquiries', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_inquiries_property_id'), 'inquiries', ['property_id'], unique=False)
    op.create_index(op.f('ix_inquiries_to_user_id'), 'inquiries', ['to_user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('demand_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demand_id', 'property_id', name='uq_match_pair')
    )
    op.create_index(op.f('ix_matches_demand_id'), 'matches', ['demand_id'], unique=False)
    op.create_index('ix_matches_property_score', 'matches', ['property_id', 'score'], unique=False)
    op.create_table('property_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('thumb_key', sa.String(length=300), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('phash', sa.String(length=16), nullable=False),
    sa.Column('blur_score', sa.Float(), nullable=False),
    sa.Column('is_blurry', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_media_property_id'), 'property_media', ['property_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_inquiry_id'), 'messages', ['inquiry_id'], unique=False)
    # ### end Alembic commands ###

    # Geography columns are generated from lat/lng so the ORM never has to write them.
    for table in GEO_TABLES:
        op.execute(f"""ALTER TABLE {table} ADD COLUMN geog geography(Point, 4326)
            GENERATED ALWAYS AS (CASE WHEN lat IS NULL OR lng IS NULL THEN NULL
                                 ELSE ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography END) STORED""")
        op.execute(f"CREATE INDEX ix_{table}_geog ON {table} USING gist (geog)")
    # Duplicate detection (trigram similarity) and hot query paths.
    op.execute("CREATE INDEX ix_demands_text_trgm ON demands USING gin "
               "(lower(title || ' ' || coalesce(description, '')) gin_trgm_ops)")
    op.execute("CREATE INDEX ix_demands_live_support ON demands (verified_support_count DESC) "
               "WHERE status IN ('published', 'growing', 'matched')")
    op.create_index("ix_demand_supports_user_created", "demand_supports", ["user_id", "created_at"])
    op.create_index("ix_matches_demand", "matches", ["demand_id", "score"])
    op.create_index("ix_reward_ledger_pending", "reward_ledger", ["status", "expected_unlock_at"])
    op.create_index("ix_audit_events_subject", "audit_events", ["subject_type", "subject_id"])
    op.create_index("ix_notifications_user_unread", "notifications", ["user_id", "read_at"])
    op.create_index("ix_inquiries_to_user", "inquiries", ["to_user_id", "last_message_at"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_inquiry_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_property_media_property_id'), table_name='property_media')
    op.drop_table('property_media')
    op.drop_index('ix_matches_property_score', table_name='matches')
    op.drop_index(op.f('ix_matches_demand_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_inquiries_to_user_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_property_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_from_user_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_demand_id'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_demand_supports_user_id'), table_name='demand_supports')
    op.drop_index(op.f('ix_demand_supports_demand_id'), table_name='demand_supports')
    op.drop_table('demand_supports')
    op.drop_index(op.f('ix_demand_interests_user_id'), table_name='demand_interests')
    op.drop_index(op.f('ix_demand_interests_demand_id'), table_name='demand_interests')
    op.drop_table('demand_interests')
    op.drop_index(op.f('ix_verifications_subject_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_status'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_saved_items_user_id'), table_name='saved_items')
    op.drop_table('saved_items')
    op.drop_index(op.f('ix_reward_ledger_user_id'), table_name='reward_ledger')
    op.drop_table('reward_ledger')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_area_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_demands_status'), table_name='demands')
    op.drop_index(op.f('ix_demands_category'), table_name='demands')
    op.drop_index(op.f('ix_demands_author_id'), table_name='demands')
    op.drop_index(op.f('ix_demands_area_id'), table_name='demands')
    op.drop_table('demands')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_challenges_destination'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_opportunity_areas_city'), table_name='opportunity_areas')
    op.drop_table('opportunity_areas')
    op.drop_index(op.f('ix_audit_events_name'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
